---
  - name: Provisioning EC2 instances using Ansible
    hosts: localhost
    connection: local
    gather_facts: False
    tags: provisioning

    vars:  
      keypair: TestingDeployingInstancesKey-Pair
      instance_type: t2.micro
      image: "ami-023adaba598e661ac"
      wait: yes
      group: webserver
      count: 1
      region: eu-central-1
      security_group: MySecurityGroup

    roles:
      - ec2_instance_launch
      - ec2_instance_tagging
      - security_group
      - ecr_setup
      - ecs_setup

