---
- name: Start EC2 instances
  hosts: localhost
  gather_facts: false
  vars:
    region: us-east-2
    instance_ids:
      - "i-033a813eba46a021c"
      - "i-0710aad6a911d69e1"
      # Add more instance IDs as needed
  tasks:
    - name: Start EC2 instances
      ec2_instance:
        state: started
        instance_ids: "{{ instance_ids }}"
        region: "{{ region }}"
      register: started_instances
