---
  - name: Add Tagging to EC2 instance
    ec2_tag:
      resource: "{{ item.instance_id}}"
      region: "{{ region }}"
      state: present
      tags:
        Name: Testing-Launching-Instances-Using-Ansible
    with_items: "{{ ec2_result.instances }}"
