---
  - name: Launch the new EC2 Instance
    local_action:
      module: ec2_instance      
      key_name: "{{ keypair }}"
      instance_type: "{{ instance_type }}"
      image_id: "{{ image }}" 
      wait: "{{ wait }}"
      security_group: "{{ security_group }}"
      count: "{{ count }}"
      region: "{{ region }}"
    register: ec2_result
