- name: create ECS service on VPC network
  community.aws.ecs_service:
    state: present
    name: console-test-service
    cluster: new_cluster_7
    task_definition: new-cluster-task-defi:3
    desired_count: 0
    network_configuration:
      subnets:
        - subnet-00a0d194ae94876ff  # This subnets are defaults
        - subnet-09536a83ab125e3fc
        - subnet-0833acf3284c99c74

      security_groups:
        - sg-076f0593678453608 
        - sg-0b48d8abddc9d4eea  # Replace this with the correct security group ID
