---
- name: Create Lambda function
  tasks:
    - name: Create Lambda function
      vars:
        function_name: my_lambda_function
        runtime: python3.8
        handler: lambda_function.lambda_handler
        role_arn: arn:aws:iam::123456789012:role/lambda-role
        zip_file: /path/to/lambda_function.zip
      vars_files:
        - vars/aws_credentials.yml
      delegate_to: localhost
      become: no
      python:
        boto3:
          region: eu-central-1 
          aws_access_key: "{{ aws_access_key }}"
          aws_secret_key: "{{ aws_secret_key }}"
          name: lambda
          module_name: lambda
          action: create_function
          kwargs:
            FunctionName: "{{ function_name }}"
            Runtime: "{{ runtime }}"
            Role: "{{ role_arn }}"
            Handler: "{{ handler }}"
            Code: 
              ZipFile: "{{ lookup('file', zip_file) }}"
            Timeout: 60
            MemorySize: 128
